### PR TITLE
Was created the project following instructions of card (kick Off) on …

### PR DESCRIPTION
**Pull request by EduardoContreras**
**Summary**

- This Pull Request contains all necessary to init development of next features.
- Was created the project following instructions of card (kick Off) on Trello. Contains all necessary to init development of next features.

**Trello Card** 
https://trello.com/c/IiFzNmuE/1-kick-off

### CODE REVIEW

**Comment by Atixx** [comment]
Put the entire project in the root folder (instead of in `/training`), this will also make sure the `.gitignore` works so you don't upload the entire `node_modules` folder and other unnecessary files

**Review by Atixx — APPROVED** [review]

**Review by gonziesc — CHANGES_REQUESTED** [review]
Would you add logs to gitigmore?

R: Yes, I was added log to gitignore file for not tracking on git.

**Comment by EduardoContreras** [comment]
@gonziesc Yes, I was added log to gitignore file for not tracking on git.

**Comment by gonziesc** [comment]
@EduardoContreras please copy the gitignore as it is on the bootstrap

**Comment by EduardoContreras** [comment]
@gonziesc done, I put gitignore as the bootstrap

**Review by gonziesc — APPROVED** [review]

**Pull request merged**
